##########
# collectionbuilder-csv
# Jekyll Digital Collection Generator
##########

#########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: "https://archive.georgecoates.com"
# path to location on the domain if necessary
baseurl: ""
# location of code, the full URL to your GitHub repository
source-code: "https://github.com/haneensid/georgecoatesarchive"

##########
# SITE SETTINGS
#
title: "The George Coates Archive"
tagline: ""
description: "Audiovisual media from George Coates Performance Works' pioneering avant-garde multimedia theater."
keywords: "george coates; rare area; actual sho; george coates performance works; avant-garde theater; new media"
author: "CollectionBuilder"

##########
# COLLECTION SETTINGS
#
# CSV filename in _data, without the .csv extension
metadata: GCARCHIVEMETADATA0818

##########
# ORGANIZATION SETTINGS
#
organization-name: "George Coates Performance Works"
organization-link: ""
organization-logo-banner: "https://imglink.cc/cdn/4iVmVEQ3xV.png"
organization-logo-nav: "https://imglink.cc/cdn/4iVmVEQ3xV.png"

##########
# ROBOTS EXCLUDE
#
# noindex: true

##########
# BUILD SETTINGS
#
lib-assets: /assets/lib
exclude:
  - docs/
  - Rakefile
  - rakelib/
  - README.md
  - LICENSE
  - CITATION.cff
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - SECURITY.md

sass:
  style: compressed
